debug: true
contextTimeout: 5

server:
    port: ':9900'

database:
    driver: 'mysql'
    host: 'localhost'
    port: 3306
    username: 'root'
    password: 'root.123456'
    name: 'rgpi'
    charset: 'utf8'
    base: 'rgpi'
redis:
    port: 6379
    host: 'localhost'
    username: ''
    password: ''
    db: 0
cors:
    allowOrigins:
        - '*'
    allowMethods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
    allowHeaders:
        - Origin
        - Authorization
        - Content-Type
        - Accept
    exposeHeaders:
        - Content-Length
    AllowCredentials: true
captcha:
    expiration: 180
jwt:
    secret: 'WXlqEk8BJXmAjtp'
    expiration: 2592000000000000
    ignores:
        - '/user/login'
        - '/user/register'
        - '/user/captcha'
email:
    from: 'z.yuexin@foxmail.com'
    password: 'yklpieacwbttjfif'
    smtp: 'smtp.qq.com'
    port: 465
