# 国际化错误提示信息
fail:
    zh_CN: 失败
    en_US: Fail
    zh_TW: 失敗
warning:
    zh_CN: 警告
    en_US: Warning
    zh_TW: 警告
server_error:
    zh_CN: 服务器错误
    en_US: Internal Server Error
    zh_TW: 服務器錯誤
invalid_params:
    zh_CN: 参数错误
    en_US: Invalid Parameters
    zh_TW: 參數錯誤
user_exits:
    zh_CN: 用户已存在
    en_US: User Exists
    zh_TW: 用戶已存在
user_not_found:
    zh_CN: 用户不存在
    en_US: User Not Found
    zh_TW: 用戶不存在
email_invalid:
    zh_CN: 邮箱格式错误
    en_US: Invalid Email
    zh_TW: 郵箱格式錯誤
email_is_registered:
    zh_CN: 邮箱已注册过，可以直接登录
    en_US: Email is registered. You can login directly
    zh_TW: 郵箱已註冊過，可以直接登錄
email_is_not_registered:
    zh_CN: 该邮箱未被注册，请注册后再登录
    en_US: Email is not registered. Please register and login again
    zh_TW: 該郵箱未被註冊，請註冊後再登錄
email_is_required:
    zh_CN: 邮箱不能为空
    en_US: Email is required
    zh_TW: 郵箱不能爲空
captcha_is_not_correct:
    zh_CN: 验证码错误
    en_US: Captcha is not correct
    zh_TW: 驗證碼錯誤
captcha_is_expired:
    zh_CN: 验证码已过期
    en_US: Captcha is expired
    zh_TW: 驗證碼已過期
captcha_has_been_sent:
    zh_CN: 验证码重复发送，稍后再试
    en_US: Send the captch repeatedly. Try again later
    zh_TW: 驗證碼重複發送，稍後再試
register_fail:
    zh_CN: 注册失败
    en_US: Register Fail
    zh_TW: 註冊失敗
password_is_wrong:
    zh_CN: 密码错误
    en_US: Password is wrong
    zh_TW: 密碼錯誤
token_create_failed:
    zh_CN: 创建token失败
    en_US: Create Token Failed
    zh_TW: 創建token失敗
